# Utsusemi Homebrew service logs. Replace @HOMEBREW_PREFIX@ with $(brew --prefix).
# logfilename                          mode  count  size(KB)  when  flags
@HOMEBREW_PREFIX@/var/log/utsusemi.log       644  7      10240     *     J
@HOMEBREW_PREFIX@/var/log/utsusemi.error.log 644  7      10240     *     J
