# Utsusemi Homebrew service logs (install with brew --prefix substitution).
# logfilename                          mode  count  size(KB)  when  flags
@HOMEBREW_PREFIX@/var/log/utsusemi.log       644  7      10240     *     J
@HOMEBREW_PREFIX@/var/log/utsusemi.error.log 644  7      10240     *     J
